project:
  type: website

site-url: "https://github.com/Addisu-Amare"

output-dir: _site

website:
  title: "Addisu Amare"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Scholarship
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Publications
        href: publications.qmd
      - text: Talks & Workshops
        href: talks.qmd
      - text: Blog
        href: blog.qmd
      - text: projects
        href: project.qmd
      - text: My Hobbies
        href: Hobbies.qmd
      -file: document_/under_graduate_work.pdf
        text : Thesis

    right:
      - icon: github
        href: https://github.com/Addisu-Amare

format:
  html:
    theme: minty
    css: css/styles.css   # optional custom CSS
    toc: false
